### ISSUE TITLE
Configure profile for AWS eb CLI

### ISSUE THREAD

**Issue by KrustyHack** [abyss/awsp-plus#8]
Ay,

Nice works ! But I think there is missing something. It correctly set `AWS_PROFILE` but for ElasticBeanStalk CLI the export variable must be `AWS_EB_PROFILE`.

Do you think it possible to add that ?

Regards,

**Comment by abyss** [comment]
Sorry for the delay in responding!

Your approach seems as reasonable as any. I'm currently in the process of a large move so it will be awhile before I have a chance to break out the code. If you want to speed it up, feel free to submit a PR :)

In the mean time, as a hotfix, you can easily modify the recommended alias to add the same functionality, like so:
```
alias awsp="source _awspp && export AWS_EB_PROFILE=$AWS_PROFILE"
```

**Comment by KrustyHack** [comment]
Ay,

No worries, thanks for your work on this repository ! ;)

You're solution seems simpler than mine haha, thanks for the idea.
